server:
  port: 9003

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

spring:
  application:
    name: oauth

  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    host: ${LONGMARCH_REDIS_IP:127.0.0.1}
    port: ${LONGMARCH_REDIS_PORT:6379}
    ## Redis服务器连接密码（默认为空）
    password: ${LONGMARCH_REDIS_PWD:}
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 50
        min-idle: 0